name: Publish (Base Images)

on:
  release:
    types: [published]
  push:
  schedule:

    # Everyday Wednesday on 01:32 UTC.  This timing is handy because while
    # European countries are in midnight, American countries are still in
    # their evening and Asian countries are in the next morning.
    - cron: '32 1 * * 3'

jobs:
  push:
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { os: 'bionic',  baseruby: '2.5', tag: 'ubuntu-18.04' }
          - { os: 'focal',   baseruby: '2.7', tag: 'ubuntu-20.04' }
          - { os: 'hirsute', baseruby: '2.7', tag: 'ubuntu-21.04' }
          - { os: 'impish',  baseruby: '2.7', tag: 'ubuntu-21.10' }

    name: Publish ${{ matrix.entry.tag }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
          registry: ghcr.io
      - uses: docker/build-push-action@v2
        with:
          build-args: |
            version=${{ matrix.entry.os }}
            baseruby=${{ matrix.entry.baseruby }}
            packages=
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          platforms: 'linux/amd64,linux/arm64'
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.entry.tag }}

      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
